
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package cp.html;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TH = 13;
  public static final int SLASH_GREATER_THAN = 30;
  public static final int TD = 15;
  public static final int EQUAL = 31;
  public static final int GREATER_THAN = 28;
  public static final int COLOR = 20;
  public static final int P = 17;
  public static final int ALIGN = 22;
  public static final int ALIGN_VALUE = 25;
  public static final int H6 = 11;
  public static final int H5 = 10;
  public static final int H4 = 9;
  public static final int H3 = 8;
  public static final int TABLE = 12;
  public static final int H2 = 7;
  public static final int H1 = 6;
  public static final int HEAD = 3;
  public static final int TITLE = 5;
  public static final int EOF = 0;
  public static final int COLOR_VALUE = 24;
  public static final int LESS_THAN = 27;
  public static final int DIV = 16;
  public static final int TEXTCOLOR = 21;
  public static final int BR = 18;
  public static final int error = 1;
  public static final int CLOSING_LESS_THAN = 29;
  public static final int HR = 19;
  public static final int BODY = 4;
  public static final int HTML = 2;
  public static final int TR = 14;
  public static final int FONT = 23;
  public static final int FONT_VALUE = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML",
  "HEAD",
  "BODY",
  "TITLE",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "TABLE",
  "TH",
  "TR",
  "TD",
  "DIV",
  "P",
  "BR",
  "HR",
  "COLOR",
  "TEXTCOLOR",
  "ALIGN",
  "FONT",
  "COLOR_VALUE",
  "ALIGN_VALUE",
  "FONT_VALUE",
  "LESS_THAN",
  "GREATER_THAN",
  "CLOSING_LESS_THAN",
  "SLASH_GREATER_THAN",
  "EQUAL"
  };
}

