
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 10;
  public static final int EOF = 0;
  public static final int OPEN_BRACES = 2;
  public static final int DOUBLEPOINT = 7;
  public static final int ID = 9;
  public static final int EXPNUMBER = 8;
  public static final int CLOSING_SQR_BRACES = 5;
  public static final int error = 1;
  public static final int OPEN_SQR_BRACES = 4;
  public static final int COMMA = 6;
  public static final int CLOSING_BRACES = 3;
  public static final int NULL_VALUE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_BRACES",
  "CLOSING_BRACES",
  "OPEN_SQR_BRACES",
  "CLOSING_SQR_BRACES",
  "COMMA",
  "DOUBLEPOINT",
  "EXPNUMBER",
  "ID",
  "BOOL",
  "NULL_VALUE"
  };
}

