
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package cp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 26;
  public static final int AR_SUB = 13;
  public static final int STRING_LITERAL = 32;
  public static final int EXPNUMBER = 29;
  public static final int CLOSING_PARENTHESIS = 3;
  public static final int CHAR_LITERAL = 33;
  public static final int ENTERO = 7;
  public static final int NOT_EQUAL = 21;
  public static final int GREATER_THAN = 17;
  public static final int GREATEQUAL_THAN = 19;
  public static final int SEMICOLON = 5;
  public static final int CARACTER = 9;
  public static final int COMMA = 4;
  public static final int EXPID = 31;
  public static final int BTRUE = 34;
  public static final int AR_DIV = 15;
  public static final int EOF = 0;
  public static final int DECIMAL = 10;
  public static final int MINUSMINUS = 27;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int EXPDECIMAL = 30;
  public static final int BEQUAL = 25;
  public static final int AR_MUL = 14;
  public static final int OPEN_PARENTHESIS = 2;
  public static final int AR_MOD = 16;
  public static final int LESSEQUAL_THAN = 20;
  public static final int ORBOP = 23;
  public static final int ANDBOP = 22;
  public static final int BOOLEANO = 8;
  public static final int NOTBOP = 24;
  public static final int TEXTO = 11;
  public static final int AR_SUM = 12;
  public static final int LESS_THAN = 18;
  public static final int BFALSE = 35;
  public static final int PRINT = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_PARENTHESIS",
  "CLOSING_PARENTHESIS",
  "COMMA",
  "SEMICOLON",
  "EQUAL",
  "ENTERO",
  "BOOLEANO",
  "CARACTER",
  "DECIMAL",
  "TEXTO",
  "AR_SUM",
  "AR_SUB",
  "AR_MUL",
  "AR_DIV",
  "AR_MOD",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATEQUAL_THAN",
  "LESSEQUAL_THAN",
  "NOT_EQUAL",
  "ANDBOP",
  "ORBOP",
  "NOTBOP",
  "BEQUAL",
  "PLUSPLUS",
  "MINUSMINUS",
  "PRINT",
  "EXPNUMBER",
  "EXPDECIMAL",
  "EXPID",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BTRUE",
  "BFALSE"
  };
}

