/* The following code was generated by JFlex 1.4.3 on 4/2/18 10:27 PM */

package javacompiler;
import java_cup.runtime.Symbol;
import proyectdata.Proyect; 
import ui.Reporter;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/2/18 10:27 PM from the specification file
 * <tt>src/javacompiler/lexical.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int READ_STRING = 2;
  public static final int FINISH_READING_CHAR = 6;
  public static final int YYINITIAL = 0;
  public static final int READ_CHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  8,  0,  6,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6, 21, 48,  0,  0, 24, 47, 50, 11, 12, 10, 22, 15, 23,  2,  9, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 17, 16, 20, 18, 19,  0, 
     0,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 
     5,  5,  5, 42,  5,  5,  5,  5,  5,  5,  5,  0, 49,  0,  0,  4, 
     0, 31, 38, 32, 40, 35, 43, 34, 37, 25,  5, 33, 39, 26, 36, 28, 
    27,  5, 29, 44, 30, 41, 45, 46,  5,  5,  5, 13,  7, 14,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\2\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\17\4\1\1"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\0"+
    "\1\35\1\36\1\0\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\2\4\1\45\16\4\1\46\10\4\1\47\1\50"+
    "\1\51\1\52\1\53\1\2\1\36\1\0\1\4\1\54"+
    "\13\4\1\55\6\4\1\56\13\4\1\57\1\4\1\60"+
    "\1\61\1\4\1\62\2\4\1\63\6\4\1\64\10\4"+
    "\1\65\1\4\1\66\2\4\1\67\1\70\2\4\1\71"+
    "\1\72\3\4\1\73\1\74\2\4\1\75\1\76\1\77"+
    "\1\100\1\101\1\4\1\102\1\4\1\103\1\4\1\104"+
    "\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\314\0\u0132"+
    "\0\314\0\u0165\0\u0198\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\314\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594"+
    "\0\u05c7\0\u05fa\0\314\0\314\0\u062d\0\314\0\u0660\0\314"+
    "\0\314\0\u0693\0\314\0\u06c6\0\u06f9\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\u072c\0\u075f\0\u0132\0\u0792\0\u07c5"+
    "\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d"+
    "\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5"+
    "\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\314\0\314\0\314"+
    "\0\314\0\314\0\u0693\0\314\0\u0c27\0\u0c5a\0\u0132\0\u0c8d"+
    "\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25"+
    "\0\u0e58\0\u0e8b\0\u0132\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a"+
    "\0\u0fbd\0\u0132\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef"+
    "\0\u1122\0\u1155\0\u1188\0\u11bb\0\u11ee\0\u0132\0\u1221\0\u0132"+
    "\0\u0132\0\u1254\0\u0132\0\u1287\0\u12ba\0\u0132\0\u12ed\0\u1320"+
    "\0\u1353\0\u1386\0\u13b9\0\u13ec\0\u0132\0\u141f\0\u1452\0\u1485"+
    "\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\u0132\0\u15b7\0\u0132"+
    "\0\u15ea\0\u161d\0\u0132\0\u0132\0\u1650\0\u1683\0\u0132\0\u0132"+
    "\0\u16b6\0\u16e9\0\u171c\0\u0132\0\u0132\0\u174f\0\u1782\0\u0132"+
    "\0\u0132\0\u0132\0\u0132\0\u0132\0\u17b5\0\u0132\0\u17e8\0\u0132"+
    "\0\u181b\0\u0132\0\u0132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\5\1\10\1\11\1\12"+
    "\1\11\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\10\1\34\1\10\1\35\1\36\1\10"+
    "\1\37\2\10\1\40\1\41\1\10\1\42\1\43\1\44"+
    "\1\10\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\5\1\54\10\55\1\5\47\55\1\56\1\57\1\55"+
    "\63\60\62\5\1\61\64\0\1\6\1\62\61\0\1\10"+
    "\2\0\2\10\23\0\26\10\13\0\1\63\64\0\1\64"+
    "\1\65\72\0\1\66\62\0\1\67\62\0\1\70\62\0"+
    "\1\71\66\0\1\72\63\0\1\73\34\0\1\10\2\0"+
    "\2\10\23\0\1\10\1\74\11\10\1\75\6\10\1\76"+
    "\3\10\5\0\1\10\2\0\2\10\23\0\4\10\1\77"+
    "\1\10\1\100\11\10\1\101\5\10\5\0\1\10\2\0"+
    "\2\10\23\0\12\10\1\102\13\10\5\0\1\10\2\0"+
    "\2\10\23\0\4\10\1\103\21\10\5\0\1\10\2\0"+
    "\2\10\23\0\3\10\1\104\2\10\1\105\5\10\1\106"+
    "\1\10\1\107\7\10\5\0\1\10\2\0\2\10\23\0"+
    "\16\10\1\110\7\10\5\0\1\10\2\0\2\10\23\0"+
    "\12\10\1\111\13\10\5\0\1\10\2\0\2\10\23\0"+
    "\3\10\1\112\1\113\21\10\5\0\1\10\2\0\2\10"+
    "\23\0\3\10\1\114\22\10\5\0\1\10\2\0\2\10"+
    "\23\0\3\10\1\115\22\10\5\0\1\10\2\0\2\10"+
    "\23\0\5\10\1\116\20\10\5\0\1\10\2\0\2\10"+
    "\23\0\1\117\2\10\1\120\2\10\1\121\17\10\5\0"+
    "\1\10\2\0\2\10\23\0\5\10\1\122\17\10\1\123"+
    "\5\0\1\10\2\0\2\10\23\0\3\10\1\124\22\10"+
    "\5\0\1\10\2\0\2\10\23\0\14\10\1\125\11\10"+
    "\63\0\1\126\3\0\10\55\1\0\47\55\2\0\1\55"+
    "\35\0\1\127\1\130\5\0\1\131\13\0\1\132\3\0"+
    "\1\133\61\0\10\64\1\134\52\64\12\65\1\135\50\65"+
    "\1\0\1\10\2\0\2\10\23\0\2\10\1\136\23\10"+
    "\5\0\1\10\2\0\2\10\23\0\5\10\1\137\20\10"+
    "\5\0\1\10\2\0\2\10\23\0\1\140\2\10\1\141"+
    "\22\10\5\0\1\10\2\0\2\10\23\0\7\10\1\142"+
    "\16\10\5\0\1\10\2\0\2\10\23\0\15\10\1\143"+
    "\10\10\5\0\1\10\2\0\2\10\23\0\5\10\1\144"+
    "\20\10\5\0\1\10\2\0\2\10\23\0\20\10\1\145"+
    "\5\10\5\0\1\10\2\0\2\10\23\0\13\10\1\146"+
    "\12\10\5\0\1\10\2\0\2\10\23\0\23\10\1\147"+
    "\2\10\5\0\1\10\2\0\2\10\23\0\6\10\1\150"+
    "\17\10\5\0\1\10\2\0\2\10\23\0\6\10\1\151"+
    "\17\10\5\0\1\10\2\0\2\10\23\0\23\10\1\152"+
    "\2\10\5\0\1\10\2\0\2\10\23\0\25\10\1\153"+
    "\5\0\1\10\2\0\2\10\23\0\3\10\1\154\22\10"+
    "\5\0\1\10\2\0\2\10\23\0\12\10\1\155\13\10"+
    "\5\0\1\10\2\0\2\10\23\0\13\10\1\156\12\10"+
    "\5\0\1\10\2\0\2\10\23\0\20\10\1\157\5\10"+
    "\5\0\1\10\2\0\2\10\23\0\4\10\1\160\21\10"+
    "\5\0\1\10\2\0\2\10\23\0\13\10\1\161\12\10"+
    "\5\0\1\10\2\0\2\10\23\0\4\10\1\162\21\10"+
    "\5\0\1\10\2\0\2\10\23\0\16\10\1\163\7\10"+
    "\5\0\1\10\2\0\2\10\23\0\6\10\1\164\17\10"+
    "\5\0\1\10\2\0\2\10\23\0\1\165\25\10\5\0"+
    "\1\10\2\0\2\10\23\0\1\166\25\10\5\0\1\10"+
    "\2\0\2\10\23\0\1\167\25\10\4\0\11\65\1\134"+
    "\1\135\50\65\1\0\1\10\2\0\2\10\23\0\3\10"+
    "\1\170\22\10\5\0\1\10\2\0\2\10\23\0\24\10"+
    "\1\171\1\10\5\0\1\10\2\0\2\10\23\0\5\10"+
    "\1\172\20\10\5\0\1\10\2\0\2\10\23\0\10\10"+
    "\1\173\15\10\5\0\1\10\2\0\2\10\23\0\16\10"+
    "\1\174\7\10\5\0\1\10\2\0\2\10\23\0\20\10"+
    "\1\175\5\10\5\0\1\10\2\0\2\10\23\0\12\10"+
    "\1\176\13\10\5\0\1\10\2\0\2\10\23\0\5\10"+
    "\1\177\20\10\5\0\1\10\2\0\2\10\23\0\12\10"+
    "\1\200\13\10\5\0\1\10\2\0\2\10\23\0\4\10"+
    "\1\201\21\10\5\0\1\10\2\0\2\10\23\0\23\10"+
    "\1\202\2\10\5\0\1\10\2\0\2\10\23\0\12\10"+
    "\1\203\13\10\5\0\1\10\2\0\2\10\23\0\16\10"+
    "\1\204\7\10\5\0\1\10\2\0\2\10\23\0\6\10"+
    "\1\205\17\10\5\0\1\10\2\0\2\10\23\0\11\10"+
    "\1\206\14\10\5\0\1\10\2\0\2\10\23\0\15\10"+
    "\1\207\10\10\5\0\1\10\2\0\2\10\23\0\1\210"+
    "\25\10\5\0\1\10\2\0\2\10\23\0\6\10\1\211"+
    "\17\10\5\0\1\10\2\0\2\10\23\0\23\10\1\212"+
    "\2\10\5\0\1\10\2\0\2\10\23\0\5\10\1\213"+
    "\20\10\5\0\1\10\2\0\2\10\23\0\5\10\1\214"+
    "\20\10\5\0\1\10\2\0\2\10\23\0\17\10\1\215"+
    "\6\10\5\0\1\10\2\0\2\10\23\0\16\10\1\216"+
    "\7\10\5\0\1\10\2\0\2\10\23\0\4\10\1\217"+
    "\21\10\5\0\1\10\2\0\2\10\23\0\6\10\1\220"+
    "\17\10\5\0\1\10\2\0\2\10\23\0\12\10\1\221"+
    "\13\10\5\0\1\10\2\0\2\10\23\0\6\10\1\222"+
    "\17\10\5\0\1\10\2\0\2\10\23\0\1\223\25\10"+
    "\5\0\1\10\2\0\2\10\23\0\4\10\1\224\21\10"+
    "\5\0\1\10\2\0\2\10\23\0\1\225\25\10\5\0"+
    "\1\10\2\0\2\10\23\0\23\10\1\226\2\10\5\0"+
    "\1\10\2\0\2\10\23\0\12\10\1\227\13\10\5\0"+
    "\1\10\2\0\2\10\23\0\10\10\1\230\15\10\5\0"+
    "\1\10\2\0\2\10\23\0\16\10\1\231\7\10\5\0"+
    "\1\10\2\0\2\10\23\0\13\10\1\232\12\10\5\0"+
    "\1\10\2\0\2\10\23\0\16\10\1\233\7\10\5\0"+
    "\1\10\2\0\2\10\23\0\12\10\1\234\13\10\5\0"+
    "\1\10\2\0\2\10\23\0\1\235\25\10\5\0\1\10"+
    "\2\0\2\10\23\0\7\10\1\236\16\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\237\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\5\10\1\240\20\10\5\0\1\10"+
    "\2\0\2\10\23\0\5\10\1\241\20\10\5\0\1\10"+
    "\2\0\2\10\23\0\7\10\1\242\16\10\5\0\1\10"+
    "\2\0\2\10\23\0\11\10\1\243\14\10\5\0\1\10"+
    "\2\0\2\10\23\0\7\10\1\244\16\10\5\0\1\10"+
    "\2\0\2\10\23\0\13\10\1\245\12\10\5\0\1\10"+
    "\2\0\2\10\23\0\13\10\1\246\12\10\5\0\1\10"+
    "\2\0\2\10\23\0\6\10\1\247\17\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\250\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\11\10\1\251\14\10\5\0\1\10"+
    "\2\0\2\10\23\0\7\10\1\252\16\10\5\0\1\10"+
    "\2\0\2\10\23\0\14\10\1\253\11\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\254\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\5\10\1\255\20\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\256\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\20\10\1\257\5\10\5\0\1\10"+
    "\2\0\2\10\23\0\13\10\1\260\12\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\261\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\12\10\1\262\13\10\5\0\1\10"+
    "\2\0\2\10\23\0\17\10\1\263\6\10\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6222];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\1\1\1\11\2\1\10\11"+
    "\6\1\1\11\20\1\2\11\1\1\1\11\1\1\2\11"+
    "\1\0\1\11\1\1\1\0\6\11\32\1\5\11\1\1"+
    "\1\11\1\0\126\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[179];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private StringBuffer string = new StringBuffer();
    private Proyect proyect = new Proyect();
    
    public void setProyect(Proyect p){
        proyect = p;
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn, yytext());
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 37: 
          { return symbol(sym.IFCOND);
          }
        case 70: break;
        case 44: 
          { return symbol(sym.INTGR);
          }
        case 71: break;
        case 69: 
          { return symbol(sym.PROVIS);
          }
        case 72: break;
        case 10: 
          { return symbol(sym.OPEN_BRACES);
          }
        case 73: break;
        case 41: 
          { string.append('\t');
          }
        case 74: break;
        case 45: 
          { return symbol(sym.NEWDEC);
          }
        case 75: break;
        case 8: 
          { return symbol(sym.OPEN_PARENTHESIS);
          }
        case 76: break;
        case 56: 
          { return symbol(sym.BFALSE);
          }
        case 77: break;
        case 3: 
          { return symbol(sym.POINT);
          }
        case 78: break;
        case 16: 
          { return symbol(sym.GREATER_THAN);
          }
        case 79: break;
        case 36: 
          { return symbol(sym.MINUSMINUS);
          }
        case 80: break;
        case 46: 
          { return symbol(sym.FORLOOP);
          }
        case 81: break;
        case 26: 
          { string.append('\\');
          }
        case 82: break;
        case 52: 
          { return symbol(sym.VOIDTYPE);
          }
        case 83: break;
        case 38: 
          { return symbol(sym.DOLOOP);
          }
        case 84: break;
        case 34: 
          { return symbol(sym.NOT_EQUAL);
          }
        case 85: break;
        case 40: 
          { string.append('\r');
          }
        case 86: break;
        case 33: 
          { return symbol(sym.LESSEQUAL_THAN);
          }
        case 87: break;
        case 2: 
          { return symbol(sym.EXPNUMBER);
          }
        case 88: break;
        case 64: 
          { return symbol(sym.SWITCHCOND);
          }
        case 89: break;
        case 5: 
          { ;
          }
        case 90: break;
        case 7: 
          { return symbol(sym.AR_MUL);
          }
        case 91: break;
        case 66: 
          { return symbol(sym.PCKGE);
          }
        case 92: break;
        case 59: 
          { return symbol(sym.PUBVIS);
          }
        case 93: break;
        case 60: 
          { return symbol(sym.RETRN);
          }
        case 94: break;
        case 53: 
          { return symbol(sym.CLASSDEC);
          }
        case 95: break;
        case 48: 
          { return symbol(sym.CASECOND);
          }
        case 96: break;
        case 67: 
          { return symbol(sym.BOOLE);
          }
        case 97: break;
        case 43: 
          { string.append('\"');
          }
        case 98: break;
        case 1: 
          { String err = "Caracter inesperado < %s >. Linea: %s. Columna: %s.";
    Reporter.err(String.format(err, yytext(), yyline, yycolumn));
          }
        case 99: break;
        case 39: 
          { return symbol(sym.ANDBOP);
          }
        case 100: break;
        case 30: 
          { proyect.addComent(yytext());
          }
        case 101: break;
        case 51: 
          { return symbol(sym.ILONG);
          }
        case 102: break;
        case 15: 
          { return symbol(sym.EQUAL);
          }
        case 103: break;
        case 50: 
          { return symbol(sym.ELSECOND);
          }
        case 104: break;
        case 29: 
          { return symbol(sym.ORBOP);
          }
        case 105: break;
        case 63: 
          { return symbol(sym.STATVIS);
          }
        case 106: break;
        case 25: 
          { yybegin(YYINITIAL); 
        return symbol(sym.STRING_LITERAL, string.toString());
          }
        case 107: break;
        case 9: 
          { return symbol(sym.CLOSING_PARENTHESIS);
          }
        case 108: break;
        case 11: 
          { return symbol(sym.CLOSING_BRACES);
          }
        case 109: break;
        case 19: 
          { return symbol(sym.AR_SUM);
          }
        case 110: break;
        case 49: 
          { return symbol(sym.CHARA);
          }
        case 111: break;
        case 32: 
          { return symbol(sym.GREATEQUAL_THAN);
          }
        case 112: break;
        case 54: 
          { return symbol(sym.BREAKCOND);
          }
        case 113: break;
        case 14: 
          { return symbol(sym.DOUBLEPOINT);
          }
        case 114: break;
        case 13: 
          { return symbol(sym.SEMICOLON);
          }
        case 115: break;
        case 42: 
          { string.append('\n');
          }
        case 116: break;
        case 35: 
          { return symbol(sym.PLUSPLUS);
          }
        case 117: break;
        case 4: 
          { return symbol(sym.EXPID);
          }
        case 118: break;
        case 6: 
          { return symbol(sym.AR_DIV);
          }
        case 119: break;
        case 22: 
          { string.setLength(0); 
    yybegin(READ_STRING);
          }
        case 120: break;
        case 28: 
          { yybegin(YYINITIAL);
        return symbol(sym.CHAR_LITERAL, string.toString());
          }
        case 121: break;
        case 55: 
          { return symbol(sym.FINAL_MOD);
          }
        case 122: break;
        case 31: 
          { return symbol(sym.BEQUAL);
          }
        case 123: break;
        case 18: 
          { return symbol(sym.NOTBOP);
          }
        case 124: break;
        case 21: 
          { return symbol(sym.AR_MOD);
          }
        case 125: break;
        case 62: 
          { return symbol(sym.STRNG);
          }
        case 126: break;
        case 20: 
          { return symbol(sym.AR_SUB);
          }
        case 127: break;
        case 27: 
          { yybegin(FINISH_READING_CHAR);
        string.append(yytext());
          }
        case 128: break;
        case 12: 
          { return symbol(sym.COMMA);
          }
        case 129: break;
        case 68: 
          { return symbol(sym.CONTINUECOND);
          }
        case 130: break;
        case 58: 
          { return symbol(sym.IMPRT);
          }
        case 131: break;
        case 17: 
          { return symbol(sym.LESS_THAN);
          }
        case 132: break;
        case 61: 
          { return symbol(sym.DOUBL);
          }
        case 133: break;
        case 47: 
          { return symbol(sym.BTRUE);
          }
        case 134: break;
        case 23: 
          { string.setLength(0);
    yybegin(READ_CHAR);
          }
        case 135: break;
        case 24: 
          { string.append( yytext() );
          }
        case 136: break;
        case 57: 
          { return symbol(sym.WHILELOOP);
          }
        case 137: break;
        case 65: 
          { return symbol(sym.PRIVIS);
          }
        case 138: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
