
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package javacompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 48;
  public static final int PCKGE = 12;
  public static final int DOUBLEPOINT = 9;
  public static final int AR_SUB = 35;
  public static final int STRING_LITERAL = 52;
  public static final int EXPNUMBER = 50;
  public static final int FINAL_MOD = 25;
  public static final int STRNG = 18;
  public static final int CLOSING_PARENTHESIS = 3;
  public static final int CHAR_LITERAL = 53;
  public static final int NOT_EQUAL = 43;
  public static final int PRIVIS = 22;
  public static final int CLASSDEC = 19;
  public static final int CHARA = 15;
  public static final int GREATER_THAN = 39;
  public static final int CLOSING_BRACES = 5;
  public static final int INTGR = 13;
  public static final int SWITCHCOND = 29;
  public static final int GREATEQUAL_THAN = 41;
  public static final int SEMICOLON = 7;
  public static final int VOIDTYPE = 26;
  public static final int COMMA = 6;
  public static final int EXPID = 51;
  public static final int BTRUE = 54;
  public static final int PUBVIS = 21;
  public static final int AR_DIV = 37;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 49;
  public static final int EQUAL = 8;
  public static final int error = 1;
  public static final int CASECOND = 30;
  public static final int BEQUAL = 47;
  public static final int RETRN = 58;
  public static final int STATVIS = 24;
  public static final int AR_MUL = 36;
  public static final int PROVIS = 23;
  public static final int DOUBL = 16;
  public static final int CONTINUECOND = 57;
  public static final int WHILELOOP = 31;
  public static final int OPEN_PARENTHESIS = 2;
  public static final int AR_MOD = 38;
  public static final int BOOLE = 14;
  public static final int IFCOND = 27;
  public static final int ELSECOND = 28;
  public static final int IMPRT = 11;
  public static final int LESSEQUAL_THAN = 42;
  public static final int POINT = 10;
  public static final int ORBOP = 45;
  public static final int ANDBOP = 44;
  public static final int NOTBOP = 46;
  public static final int ILONG = 17;
  public static final int DOLOOP = 33;
  public static final int BREAKCOND = 56;
  public static final int AR_SUM = 34;
  public static final int LESS_THAN = 40;
  public static final int FORLOOP = 32;
  public static final int BFALSE = 55;
  public static final int OPEN_BRACES = 4;
  public static final int NEWDEC = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_PARENTHESIS",
  "CLOSING_PARENTHESIS",
  "OPEN_BRACES",
  "CLOSING_BRACES",
  "COMMA",
  "SEMICOLON",
  "EQUAL",
  "DOUBLEPOINT",
  "POINT",
  "IMPRT",
  "PCKGE",
  "INTGR",
  "BOOLE",
  "CHARA",
  "DOUBL",
  "ILONG",
  "STRNG",
  "CLASSDEC",
  "NEWDEC",
  "PUBVIS",
  "PRIVIS",
  "PROVIS",
  "STATVIS",
  "FINAL_MOD",
  "VOIDTYPE",
  "IFCOND",
  "ELSECOND",
  "SWITCHCOND",
  "CASECOND",
  "WHILELOOP",
  "FORLOOP",
  "DOLOOP",
  "AR_SUM",
  "AR_SUB",
  "AR_MUL",
  "AR_DIV",
  "AR_MOD",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATEQUAL_THAN",
  "LESSEQUAL_THAN",
  "NOT_EQUAL",
  "ANDBOP",
  "ORBOP",
  "NOTBOP",
  "BEQUAL",
  "PLUSPLUS",
  "MINUSMINUS",
  "EXPNUMBER",
  "EXPID",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BTRUE",
  "BFALSE",
  "BREAKCOND",
  "CONTINUECOND",
  "RETRN"
  };
}

